#render testing
fps_tracker_enabled=true    #prints fps, frametime and rendertime to console
vsync_enabled=true
target_fps=60               #u16

#input testing
input_debug_enabled=false   #writes keypresses to console
